title: almcc.me
description: > # this means to ignore newlines until "baseurl:"
  Personal blog to record my tinkerings with new technologies.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://almcc.me" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /blog/:year/:month/:day/:title/


# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

#disqus
disqus:
  shortname: almcc-me
